# coding: utf-8

"""
    Book Info API

    書籍検索外部APIをラップする自前API。  ## 外部APIとの違い | 項目 | 外部API (Book Search API) | 本API (Book Info API) | |------|--------------------------|----------------------| | フィールド命名 | camelCase | snake_case | | エラー表現 | code + message | detail (RFC 7807風) | | 検索パラメータ | `q`, `maxResults`, `startIndex` | `keyword`, `per_page`, `page` | | ページネーション | オフセット型 (startIndex) | ページ型 (page / per_page) | | 著者表現 | `authors: string[]` | `authors: Author[]` | | 出版日 | `publishedDate: string` (精度不定) | `published_year: integer` + `published_date?: string` | | 書籍説明フィールド | `description` | `summary` | 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.books_api import router as BooksApiRouter

app = FastAPI(
    title="Book Info API",
    description="書籍検索外部APIをラップする自前API。  ## 外部APIとの違い | 項目 | 外部API (Book Search API) | 本API (Book Info API) | |------|--------------------------|----------------------| | フィールド命名 | camelCase | snake_case | | エラー表現 | code + message | detail (RFC 7807風) | | 検索パラメータ | &#x60;q&#x60;, &#x60;maxResults&#x60;, &#x60;startIndex&#x60; | &#x60;keyword&#x60;, &#x60;per_page&#x60;, &#x60;page&#x60; | | ページネーション | オフセット型 (startIndex) | ページ型 (page / per_page) | | 著者表現 | &#x60;authors: string[]&#x60; | &#x60;authors: Author[]&#x60; | | 出版日 | &#x60;publishedDate: string&#x60; (精度不定) | &#x60;published_year: integer&#x60; + &#x60;published_date?: string&#x60; | | 書籍説明フィールド | &#x60;description&#x60; | &#x60;summary&#x60; | ",
    version="1.0.0",
)

app.include_router(BooksApiRouter)
