# coding: utf-8

"""
    Book Info API

    書籍検索外部APIをラップする自前API。  ## 外部APIとの違い | 項目 | 外部API (Book Search API) | 本API (Book Info API) | |------|--------------------------|----------------------| | フィールド命名 | camelCase | snake_case | | エラー表現 | code + message | detail (RFC 7807風) | | 検索パラメータ | `q`, `maxResults`, `startIndex` | `keyword`, `per_page`, `page` | | ページネーション | オフセット型 (startIndex) | ページ型 (page / per_page) | | 著者表現 | `authors: string[]` | `authors: Author[]` | | 出版日 | `publishedDate: string` (精度不定) | `published_year: integer` + `published_date?: string` | | 書籍説明フィールド | `description` | `summary` | 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_server.models.author import Author
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class BookDetail(BaseModel):
    """
    BookDetail
    """ # noqa: E501
    isbn: StrictStr = Field(description="ISBN-13")
    title: StrictStr
    authors: Annotated[List[Author], Field(min_length=1)] = Field(description="著者・訳者の構造化リスト")
    published_year: StrictInt = Field(description="出版年（外部APIの publishedDate から年を抽出）")
    published_date: Optional[StrictStr] = Field(default=None, description="出版日（YYYY-MM-DD。精度が年単位の場合は null）")
    publisher: Optional[StrictStr] = None
    summary: Optional[StrictStr] = Field(default=None, description="書籍の説明文（外部APIの `description` フィールドをマッピング）")
    page_count: Optional[StrictInt] = None
    categories: Optional[List[StrictStr]] = None
    thumbnail_url: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["isbn", "title", "authors", "published_year", "published_date", "publisher", "summary", "page_count", "categories", "thumbnail_url"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BookDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in authors (list)
        _items = []
        if self.authors:
            for _item in self.authors:
                if _item:
                    _items.append(_item.to_dict())
            _dict['authors'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of BookDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "isbn": obj.get("isbn"),
            "title": obj.get("title"),
            "authors": [Author.from_dict(_item) for _item in obj.get("authors")] if obj.get("authors") is not None else None,
            "published_year": obj.get("published_year"),
            "published_date": obj.get("published_date"),
            "publisher": obj.get("publisher"),
            "summary": obj.get("summary"),
            "page_count": obj.get("page_count"),
            "categories": obj.get("categories"),
            "thumbnail_url": obj.get("thumbnail_url")
        })
        return _obj


